Repository PdxCodeGuild/class_australian_shepherd, pull requests merged in 2022-08, with the labels that each got.

#43 Ben b python lab03 average num
  code/amber/lab02.py
  code/ben_b/python/lab01_CodeFolder.py
  code/ben_b/python/lab02a_MadLib.py
  code/ben_b/python/lab03b_AverageNum.py
  code/ben_b/python/madlib.py
  code/matt/python/notes/notes_pre_average_numbers.py
  code/matt/python/notes/notes_pre_madlibs.py
Labels: In Review

#45 Matt r python lab 3b v1.py
  code/matt_r/python/lab_3b_avnumsv1.py
  code/matt_r/python/lab_3bavnumsv2.py
Labels: In Review

#34 submission for lab 3
  code/Justin/Python/lab_3.py
Labels: In Review

#59 Kacey python lab03
  code/kacey/labs/python/lab00/lab00.py
  code/kacey/labs/python/lab01/lab01.py
  code/kacey/labs/python/lab02/lab02.py
  code/kacey/labs/python/lab03/lab03.py
  code/kacey/labs/python/lab03/optional_make_change.py
  code/kacey/labs/python/lab03/randomnotes.py
Labels: In Review

#76 Matt r python madlib
  code/matt_r/python/lab_2b_palindrome.py
  code/matt_r/python/madlib.py
Labels: In Review

#80 Paul r alllabs
  code/paul/python/lab02a.py
  code/paul/python/lab02b.py
  code/paul/python/lab05.py
  code/paul/python/lab06.py
  code/paul/python/test.py
Labels: In Review

#66 Justin g python credit card validation
  code/Justin/Python/lab_6.py
  code/Justin/Python/lab_credit_card_validator.py
Labels: In Review

#57 lab 5a palindrome.py
  code/ignacio/lab_03b_get_average.py
  code/ignacio/lab_5a_palindrome.py
  code/ignacio/lab_6b_verification.py
  code/ignacio/madlibs.py
Labels: Question

#68 Amber python lab08 pick 6
  code/amber/python/lab08_pick6.py
Labels: In Review

#86 Nick python lab 9 blackjack
  code/nick/python/lab_8_pick6.py
  code/nick/python/lab_9_blackjack.py
Labels: In Review

#81 lab_8_pick6_update
  code/nick/python/lab_8_pick6.py
Labels: Needs correction

#79 ben_b-python-lab_RoadTrip-version1
  code/ben_b/python/lab_RoadTrip.py
Labels: Bonus Lab

#89 lab07_JackalopeSimulator with Kacey, Iggy, Tim
  code/ben_b/python/lab07_JackalopeSimulator.py
Labels: In Review

#85 Amber python roadtrip
  code/amber/python/optional_roadtrip.py
Labels: Bonus Lab

#88 Amber python socks
  code/amber/python/optional_socks.py
Labels: Bonus Lab

#90 nick-python-lab_option_peaksnvalley
  code/nick/python/lab_optional_peaksnvalleys.py
  code/nick/python/lab_optional_rot-cipher.py
Labels: Needs correction, Bonus Lab

#97 Amber python computeari
  code/amber/python/darwin.txt
  code/amber/python/lab09_compute_ari.py
Labels: In Review

#98 blackjack lab submit
  code/kacey/labs/python/lab05/lab06.py
Labels: In Review

#103 submission for ari lab
  code/Justin/Python/lab_computer_ari.py
Labels: In Review

#100 Amber python rotcipher
  code/amber/lab02.py
  code/amber/lab08_blackjack.py
  code/amber/python/lab07_rot_cipher.py
Labels: In Review, Needs correction

#107 submission for black jack advice lab
  code/Justin/Python/lab_black_jack_advice.py
Labels: In Review

#94 ben_b-python-lab_RotCipher
  code/ben_b/python/lab_RotCipher.py
Labels: In Review

#108 IgnacioR_Compute ari lab.py
  code/ignacio/python/compute-ari_lab.py
  code/ignacio/python/lab_0.py
  code/ignacio/python/lab_03b_get_average.py
  code/ignacio/python/lab_5a_palindrome.py
  code/ignacio/python/lab_6b_verification.py
  code/ignacio/python/lab_8Pick6.py
  code/ignacio/python/madlibs.py
Labels: In Review

#58 lab_6b_verification.py
  code/ignacio/lab_6b_verification.py
Labels: In Review, Needs correction

#110 ben_b-python-lab_ComputeARI
  code/ben_b/python/lab_ComputeARI.py
Labels: In Review

#114 mike_j-python-rot_cipher
  code/mike_j/python/rot_cipher.py
Labels: In Review

#121 nick-python-optional-road_trip
  code/nick/python/lab_optional_roadtrip.py
Labels: In Review, Bonus Lab

#117 Matt r python rot13
  code/matt_r/python/rot13.py
  code/matt_r/python/rot13_v2.py
Labels: In Review

#122 submission for socks
  code/Justin/Python/lab_socks.py
Labels: In Review, Bonus Lab

#125 reuploading
  code/ignacio/python/lab-11-rot_cipher.py
Labels: In Review

#111 Paul r lab 09 blackjack
  code/paul/python/lab09.py
Labels: Needs correction

#128 nick-python-lab_10_contacts
  code/nick/python/lab_10_contacts-list.py
Labels: In Review

#134 ignacio-r Lab17 contact list
  code/ignacio/python/contacts.csv
  code/ignacio/python/contacts2.csv
  code/ignacio/python/lab17_contact_list.py
Labels: In Review

#130 nick-python-lab_option_socks
  code/nick/python/lab_optional_socks.py
Labels: In Review, Bonus Lab

#139 Kacey python contacts lab10
  code/kacey/labs/lab10/contacts.csv
  code/kacey/labs/lab10/contacts.py
  code/kacey/labs/lab10/new_contacts.csv
Labels: In Review

#140 ben_b-python-lab12_ATM
  code/ben_b/python/lab12_ATM.py
Labels: In Review

#141 Amber python atm
  code/amber/python/lab12_atm.py
Labels: In Review

#142 mike_j-python-atm
  code/mike_j/python/atm.py
Labels: In Review

#144 Kacey python lab11 atm
  code/kacey/labs/lab11/lab11.py
Labels: In Review

#145 nick-python-lab_12_atm
  code/nick/python/lab_12_atm.py
Labels: In Review

#143 ignacio-r Lab8-Pick6
  code/ignacio/python/jacklopemod.py
  code/ignacio/python/lab_6b_verification.py
  code/ignacio/python/lab_8Pick6.py
  code/ignacio/python/wizard-of-oz.txt
Labels: In Review

#146 Add self.transaction_log constructor to class ATM, as well as print_t…
  code/amber/python/lab12_atm.py
Labels: In Review

#147 ignacior_lab9_blackjack
  code/ignacio/python/lab-9_blackjack.py
Labels: In Review

#119 Justin g lab pick 6.py
  code/Justin/Python/lab_pick_6.py
Labels: Needs correction

#127 Amber python contacts
  code/amber/python/lab11_contact.csv
  code/amber/python/lab11_contact_list.py
  code/amber/python/lab11_new_contact.csv
Labels: Needs correction

#150 version 1 lab_dad_joke
  code/Justin/Python/lab_dad_joke.py/lab_dad_joke.py
Labels: In Review

#152 submitting dad jokes API
  code/kacey/labs/python/lab12/dad_jokes_api.py
Labels: In Review

#153 dad joke lab
  code/matt_r/python/atm.py
  code/matt_r/python/contacts.csv
  code/matt_r/python/dadjoke.py
  code/matt_r/python/new_contacts.csv
Labels: In Review

#154 ben_b-python-lab10_DadJokeApi
  code/ben_b/python/lab10_DadJokeApi.py
Labels: In Review

#160 nick-python-lab_15_quotes_api
  code/nick/python/lab_15_quotes_api.py
Labels: In Review

#161 Mike j python quote api
  code/mike_j/python/avg_num.py
  code/mike_j/python/blackjack_adv.py
  code/mike_j/python/cc_valid.py
  code/mike_j/python/contact_list.py
  code/mike_j/python/dad_joke.py
  code/mike_j/python/hello_world.py
  code/mike_j/python/mad_lib.py
  code/mike_j/python/make_change.py
  code/mike_j/python/pal_checker.py
  code/mike_j/python/pick6.py
  code/mike_j/python/quotes_api.py
Labels: In Review

#156 mike_j-python-dad_joke
  code/mike_j/python/avg_num.py
  code/mike_j/python/blackjack_adv.py
  code/mike_j/python/cc_valid.py
  code/mike_j/python/contact_list.py
  code/mike_j/python/dad_joke.py
  code/mike_j/python/hello_world.py
  code/mike_j/python/mad_lib.py
  code/mike_j/python/make_change.py
  code/mike_j/python/pal_checker.py
  code/mike_j/python/pick6.py
Labels: Needs correction

#159 ben_b-python-lab18_QuotesApi
  code/ben_b/python/lab18_QuotesApi.py
Labels: In Review

#162 Amber python dadjokeapi
  code/amber/python/lab19_dad_jokes.py
Labels: In Review

#163 Kacey python lab13 quotes
  code/kacey/labs/python/lab13/lab13.py
Labels: In Review

#165 Ignacio r lab18 quotes api
  code/ignacio/python/lab18_quotes-api.py
Labels: In Review

#166 Amber python quotesapi
  code/amber/python/lab15_quotes_api.py
Labels: In Review

#112 Added anagram function per Mr. T
  code/paul/python/lab05.py
  code/paul/python/lab_14_ARI.py
  code/paul/python/test.txt
Labels: Needs correction

#132 First part took me a while
  code/paul/python/contacts.csv
  code/paul/python/paul_r-python_Contacts_List.py
Labels: In Review

#148 contact lab
  code/matt_r/python/contact.py
  code/matt_r/python/contacts.csv
  git
Labels: Needs correction

#170 Matt r python contact lab
  code/matt_r/python/atm.py
  code/matt_r/python/capstone/.gitignore
  code/matt_r/python/capstone/capstone.py
  code/matt_r/python/capstone/config.py
  code/matt_r/python/contacts.py
  code/matt_r/python/quotes.py
Labels: In Review
