Repository PdxCodeGuild/class_australian_shepherd, pull requests merged in 2022-11, with the labels that each got.

#308 Amber js todo mob
  code/amber/javascript/lab_todo_mob/index.html
  code/amber/javascript/lab_todo_mob/scripts.js
Labels: Bonus Lab

#313 todo with kacey
  code/matt_r/java/kacey-matt-todo/index.html
  code/matt_r/java/kacey-matt-todo/script.js
  code/matt_r/java/kacey-matt-todo/styles.css
Labels: Bonus Lab

#309 Justin graham mob lab
  code/Justin/JavaScript/mob_lab/index.html
  code/Justin/JavaScript/mob_lab/myscript.js
Labels: Bonus Lab

#314 Amber js quotes
  code/amber/javascript/lab09_quotes/index.html
  code/amber/javascript/lab09_quotes/scripts.js
Labels: Needs correction

#317 Mike j javascript quotes
  code/mike_j/javascript/quotes/index.html
  code/mike_j/javascript/quotes/script.js
Labels: Needs correction

#297 Mike j javascript todo
  code/mike_j/javascript/todo/index.html
  code/mike_j/javascript/todo/script.js
Labels: Bonus Lab

#320 Ben b javascript lab09 random quote
  code/ben_b/javascript/lab09_randomQuote/lab09_randomQuote.css
  code/ben_b/javascript/lab09_randomQuote/lab09_randomQuote.html
  code/ben_b/javascript/lab09_randomQuote/lab09_randomQuote.js
Labels: Needs correction

#299 wip
  code/matt_r/django/lab3/blog_project/Pipfile
  code/matt_r/django/lab3/blog_project/blog_app/__init__.py
  code/matt_r/django/lab3/blog_project/blog_app/admin.py
  code/matt_r/django/lab3/blog_project/blog_app/apps.py
  code/matt_r/django/lab3/blog_project/blog_app/migrations/0001_initial.py
  code/matt_r/django/lab3/blog_project/blog_app/migrations/0002_blog_body.py
  code/matt_r/django/lab3/blog_project/blog_app/migrations/0003_blog_created.py
  code/matt_r/django/lab3/blog_project/blog_app/migrations/0004_blog_author.py
  code/matt_r/django/lab3/blog_project/blog_app/migrations/0005_alter_blog_options.py
  code/matt_r/django/lab3/blog_project/blog_app/migrations/__init__.py
  code/matt_r/django/lab3/blog_project/blog_app/models.py
  code/matt_r/django/lab3/blog_project/blog_app/tests.py
  code/matt_r/django/lab3/blog_project/blog_app/urls.py
  code/matt_r/django/lab3/blog_project/blog_app/views.py
  code/matt_r/django/lab3/blog_project/blog_project/__init__.py
  code/matt_r/django/lab3/blog_project/blog_project/asgi.py
  code/matt_r/django/lab3/blog_project/blog_project/settings.py
  code/matt_r/django/lab3/blog_project/blog_project/urls.py
  code/matt_r/django/lab3/blog_project/blog_project/wsgi.py
  code/matt_r/django/lab3/blog_project/manage.py
  code/matt_r/django/lab3/blog_project/static/css/styles.css
  code/matt_r/django/lab3/blog_project/templates/base.html
  code/matt_r/django/lab3/blog_project/templates/home.html
  code/matt_r/django/lab3/blog_project/templates/post_delete.html
  code/matt_r/django/lab3/blog_project/templates/post_edit.html
  code/matt_r/django/lab3/blog_project/templates/post_new.html
  code/matt_r/django/lab3/blog_project/templates/profile.html
  code/matt_r/django/lab3/blog_project/templates/registration/login.html
  code/matt_r/django/lab3/blog_project/templates/signup.html
  code/matt_r/django/lab3/blog_project/users/__init__.py
  code/matt_r/django/lab3/blog_project/users/admin.py
  code/matt_r/django/lab3/blog_project/users/apps.py
  code/matt_r/django/lab3/blog_project/users/migrations/__init__.py
  code/matt_r/django/lab3/blog_project/users/models.py
  code/matt_r/django/lab3/blog_project/users/tests.py
  code/matt_r/django/lab3/blog_project/users/urls.py
  code/matt_r/django/lab3/blog_project/users/views.py
  code/matt_r/java/hacker/index.html
  code/matt_r/java/hacker/scripts.js
  code/matt_r/java/redo_randpass/index.html
  code/matt_r/java/redo_randpass/myscript.js
Labels: WIP

#260 grocery_list lab submission
  code/Justin/Django/Pipfile
  code/Justin/Django/grocery_list/grocery_list/__init__.py
  code/Justin/Django/grocery_list/grocery_list/asgi.py
  code/Justin/Django/grocery_list/grocery_list/settings.py
  code/Justin/Django/grocery_list/grocery_list/urls.py
  code/Justin/Django/grocery_list/grocery_list/wsgi.py
  code/Justin/Django/grocery_list/manage.py
  code/Justin/Django/grocery_list/myapp/__init__.py
  code/Justin/Django/grocery_list/myapp/admin.py
  code/Justin/Django/grocery_list/myapp/apps.py
  code/Justin/Django/grocery_list/myapp/migrations/0001_initial.py
  code/Justin/Django/grocery_list/myapp/migrations/0002_alter_mymodel_created.py
  code/Justin/Django/grocery_list/myapp/migrations/0003_rename_myauthor_mymodel_item_description_and_more.py
  code/Justin/Django/grocery_list/myapp/migrations/0004_mymodel_active_alter_mymodel_created.py
  code/Justin/Django/grocery_list/myapp/migrations/0005_remove_mymodel_active_alter_mymodel_created.py
  code/Justin/Django/grocery_list/myapp/migrations/0006_groceryitem_delete_mymodel.py
  code/Justin/Django/grocery_list/myapp/migrations/0007_groceryitem_completed_alter_groceryitem_created.py
  code/Justin/Django/grocery_list/myapp/migrations/0008_alter_groceryitem_completed_and_more.py
  code/Justin/Django/grocery_list/myapp/migrations/0009_alter_groceryitem_created.py
  code/Justin/Django/grocery_list/myapp/migrations/0010_groceryitem_updated_alter_groceryitem_created.py
  code/Justin/Django/grocery_list/myapp/migrations/__init__.py
  code/Justin/Django/grocery_list/myapp/models.py
  code/Justin/Django/grocery_list/myapp/static/background.jpg
  code/Justin/Django/grocery_list/myapp/static/favicon.png
  code/Justin/Django/grocery_list/myapp/static/git.png
  code/Justin/Django/grocery_list/myapp/static/github.png
  code/Justin/Django/grocery_list/myapp/static/linked.png
  code/Justin/Django/grocery_list/myapp/static/linkedin.png
  code/Justin/Django/grocery_list/myapp/static/stylesheet.css
  code/Justin/Django/grocery_list/myapp/templates/myapp/home.html
  code/Justin/Django/grocery_list/myapp/tests.py
  code/Justin/Django/grocery_list/myapp/urls.py
  code/Justin/Django/grocery_list/myapp/views.py
  code/Justin/Django/myproject/myapp/templates/myapp/detail.html
  code/Justin/Django/myproject/myapp/templates/myapp/home.html
  code/Justin/Django/myproject/myapp/urls.py
  code/Justin/Django/myproject/myapp/views.py
  code/Justin/Django/todo/manage.py
  code/Justin/Django/todo/todo/__init__.py
  code/Justin/Django/todo/todo/asgi.py
  code/Justin/Django/todo/todo/settings.py
  code/Justin/Django/todo/todo/urls.py
  code/Justin/Django/todo/todo/wsgi.py
  code/Justin/Django/todo/todo_list/__init__.py
  code/Justin/Django/todo/todo_list/admin.py
  code/Justin/Django/todo/todo_list/apps.py
  code/Justin/Django/todo/todo_list/migrations/__init__.py
  code/Justin/Django/todo/todo_list/models.py
  code/Justin/Django/todo/todo_list/tests.py
  code/Justin/Django/todo/todo_list/views.py
Labels: Needs correction
