Repository PdxCodeGuild/class_australian_shepherd, pull requests merged in 2022-09, with the labels that each got.

#173 mike_j-python-minicap
  code/mike_j/python/.gitignore
  code/mike_j/python/games_db.csv
  code/mike_j/python/games_db.py
Labels: WIP

#183 PaulMiniPyCap
  code/paul/python/ATM_Lab.py
  code/paul/python/Dad_Joke_Lab.py
  code/paul/python/MiniCAPSTN.py
  code/paul/python/lab05.py
Labels: In Review

#185 Paul r python py mini capstpone
  code/paul/python/MiniCAPSTN.py
Labels: In Review

#193 Kacey html css lab01
  code/kacey/labs/HTML&CSS/Ada_Lovelace_Image.jpg
  code/kacey/labs/HTML&CSS/Augusta Ada King.HTML
  code/kacey/labs/HTML&CSS/blue-code.gif
  code/kacey/labs/HTML&CSS/matrix-code.gif
  code/kacey/labs/HTML&CSS/styles.css
Labels: In Review

#194 submission for lab_bio
  code/Justin/HTML_and_CSS/lab_bio/fonts/SPACE EXPLORER.ttf
  code/Justin/HTML_and_CSS/lab_bio/images/IoM2.png
  code/Justin/HTML_and_CSS/lab_bio/images/KoM.jpg
  code/Justin/HTML_and_CSS/lab_bio/images/bullet2.png
  code/Justin/HTML_and_CSS/lab_bio/images/iomw.jpg
  code/Justin/HTML_and_CSS/lab_bio/index.html
  code/Justin/HTML_and_CSS/lab_bio/styles.css
  code/Justin/HTML_and_CSS/package-lock.json
  code/Justin/HTML_and_CSS/package.json
Labels: In Review

#189 Amber htmlcss bio
  code/amber/HTML_and_CSS/img/Aristotle.jpg
  code/amber/HTML_and_CSS/img/thot.jpg
  code/amber/HTML_and_CSS/img/tots.jpg
  code/amber/HTML_and_CSS/index.html
  code/amber/HTML_and_CSS/styles.css
Labels: In Review

#198 nick-htmlcss-lab1_bio
  code/nick/flask-html-css/lab-1-bio/index.html
  code/nick/flask-html-css/lab-1-bio/style.css
  code/nick/flask-html-css/lab-1-bio/ye-background.png
  code/nick/flask-html-css/lab-1-bio/ye-photo.jpg
Labels: In Review

#205 Kacey html css lab02
  code/kacey/labs/HTML&CSS2/facebook_logo.jpg
  code/kacey/labs/HTML&CSS2/flickrlogo.jpg
  code/kacey/labs/HTML&CSS2/image1of4.jpg
  code/kacey/labs/HTML&CSS2/image2of4.jpg
  code/kacey/labs/HTML&CSS2/image3of4.jpg
  code/kacey/labs/HTML&CSS2/image4of4.jpg
  code/kacey/labs/HTML&CSS2/index.html
  code/kacey/labs/HTML&CSS2/instagram_logo.jpg
  code/kacey/labs/HTML&CSS2/styles.css
  code/kacey/labs/HTML&CSS2/twitter_logo.jpg
Labels: In Review

#206 submission for company page lab
  code/Justin/HTML_and_CSS/lab_company/dominaria.html
  code/Justin/HTML_and_CSS/lab_company/images/MTGDominariaUnitedFP.jpg
  code/Justin/HTML_and_CSS/lab_company/images/Poke.jpg
  code/Justin/HTML_and_CSS/lab_company/images/buylist.jpg
  code/Justin/HTML_and_CSS/lab_company/images/d20.png
  code/Justin/HTML_and_CSS/lab_company/images/d202.png
  code/Justin/HTML_and_CSS/lab_company/images/dd.png
  code/Justin/HTML_and_CSS/lab_company/images/dnd.jpg
  code/Justin/HTML_and_CSS/lab_company/index.html
  code/Justin/HTML_and_CSS/lab_company/mtg.html
  code/Justin/HTML_and_CSS/lab_company/styles.css
Labels: In Review

#204 Amber htmlcss company
  code/amber/HTML_and_CSS/lab02_company/desktopstyles.css
  code/amber/HTML_and_CSS/lab02_company/img/alien.jpeg
  code/amber/HTML_and_CSS/lab02_company/img/diaper.jpeg
  code/amber/HTML_and_CSS/lab02_company/img/goddess.jpg
  code/amber/HTML_and_CSS/lab02_company/img/placenta.jpeg
  code/amber/HTML_and_CSS/lab02_company/img/space.jpeg
  code/amber/HTML_and_CSS/lab02_company/img/success.jpeg
  code/amber/HTML_and_CSS/lab02_company/img/surgery.jpeg
  code/amber/HTML_and_CSS/lab02_company/index.html
  code/amber/HTML_and_CSS/lab02_company/styles.css
  code/amber/python/art_table_report 2.json
  code/amber/python/mini_cap 2.py
  code/amber/python/minicap_objects 2.py
Labels: In Review

#197 This will be done NLT tomorrow
  code/paul/python/Quote_API_Lab.py
Labels: WIP

#213 mike_j-flask_html_css-lab3_blog
  code/mike_j/flask_html_css/lab3_blog/blog.py
  code/mike_j/flask_html_css/lab3_blog/static/css/dt_styles.css
  code/mike_j/flask_html_css/lab3_blog/static/css/mob_styles.css
  code/mike_j/flask_html_css/lab3_blog/templates/blog.html
  code/mike_j/flask_html_css/lab3_blog/templates/index.html
Labels: In Review

#215 blog lab submission
  code/Justin/HTML_and_CSS/lab_blog/bloggit.py
  code/Justin/HTML_and_CSS/lab_blog/static/GitHub-Mark-Light-32px.png
  code/Justin/HTML_and_CSS/lab_blog/static/GitHub-Mark/PNG/GitHub-Mark-120px-plus.png
  code/Justin/HTML_and_CSS/lab_blog/static/GitHub-Mark/PNG/GitHub-Mark-32px.png
  code/Justin/HTML_and_CSS/lab_blog/static/GitHub-Mark/PNG/GitHub-Mark-64px.png
  code/Justin/HTML_and_CSS/lab_blog/static/GitHub-Mark/PNG/GitHub-Mark-Light-120px-plus.png
  code/Justin/HTML_and_CSS/lab_blog/static/GitHub-Mark/PNG/GitHub-Mark-Light-64px.png
  code/Justin/HTML_and_CSS/lab_blog/static/GitHub-Mark/Vector/GitHub-Mark.ai
  code/Justin/HTML_and_CSS/lab_blog/static/GitHub-Mark/Vector/GitHub-Mark.eps
  code/Justin/HTML_and_CSS/lab_blog/static/fed.png
  code/Justin/HTML_and_CSS/lab_blog/static/styles.css
  code/Justin/HTML_and_CSS/lab_blog/templates/index.html
Labels: In Review

#217 submitting lab03 Flask Blogs
  code/kacey/labs/Flask/hello.py
  code/kacey/labs/Flask/static/css/styles.css
  code/kacey/labs/Flask/static/img/final_fake_news_logo.jpg
  code/kacey/labs/Flask/templates/about.html
  code/kacey/labs/Flask/templates/index.html
Labels: In Review

#218 nick-flask-lab_3_blog
  code/nick/flask-html-css/lab-3-blog/nick_blog.py
  code/nick/flask-html-css/lab-3-blog/static/IMG_5551.jpg
  code/nick/flask-html-css/lab-3-blog/static/styleDesktop.css
  code/nick/flask-html-css/lab-3-blog/static/styleMobile.css
  code/nick/flask-html-css/lab-3-blog/templates/index.html
  code/nick/flask-html-css/lab-3-blog/templates/randomize.html
  code/nick/flask-html-css/lab-3-blog/templates/sorted.html
Labels: In Review

#220 mike_j-flask-html-css-lab4_burrito_order_form
  code/mike_j/flask_html_css/lab4_burrito_order_form/images/burrito.jpg
  code/mike_j/flask_html_css/lab4_burrito_order_form/index.html
  code/mike_j/flask_html_css/lab4_burrito_order_form/styles.css
Labels: In Review

#221 ignacio-r_burrito_lab03
  code/ignacio/HTML_AND_CSS/01bio.html/index.html
  code/ignacio/HTML_AND_CSS/burrito order form/burrito.jpeg
  code/ignacio/HTML_AND_CSS/burrito order form/index.html
  code/ignacio/HTML_AND_CSS/burrito order form/mobilestyles.css
Labels: In Review

#223 burrito lab
  code/matt_r/html/blog_lab/bloglab.py
  code/matt_r/html/blog_lab/static/css/desktopstyles.css
  code/matt_r/html/blog_lab/templates/blogmain.html
  code/matt_r/html/burrito_lab/burrito.html
  code/matt_r/html/burrito_lab/images/burrito.PNG
  code/matt_r/html/burrito_lab/styles.css
Labels: In Review

#225 Burrito lab order form
  code/Justin/HTML_and_CSS/lab_burrito/burrito.py
  code/Justin/HTML_and_CSS/lab_burrito/static/background.png
  code/Justin/HTML_and_CSS/lab_burrito/static/burrito.jpg
  code/Justin/HTML_and_CSS/lab_burrito/static/pugrito.jpg
  code/Justin/HTML_and_CSS/lab_burrito/static/pugrito.png
  code/Justin/HTML_and_CSS/lab_burrito/static/styles.css
  code/Justin/HTML_and_CSS/lab_burrito/templates/index.html
  code/Justin/HTML_and_CSS/lab_burrito/templates/order.html
Labels: In Review

#226 Ignacio r html bio lab
  code/ignacio/HTML_AND_CSS/bio_lab01/images/davechapelle.jpeg
  code/ignacio/HTML_AND_CSS/bio_lab01/images/stage.jpeg
  code/ignacio/HTML_AND_CSS/bio_lab01/index.html
  code/ignacio/HTML_AND_CSS/bio_lab01/styles.css
Labels: In Review

#227 nick-flask-lab_4_burrito_form
  code/nick/flask-html-css/lab-4-burrito/index.html
  code/nick/flask-html-css/lab-4-burrito/static/burrito.jpg
  code/nick/flask-html-css/lab-4-burrito/static/style.css
Labels: In Review

#224 blog lab
  code/matt_r/html/blog_lab/bloglab.py
  code/matt_r/html/blog_lab/static/css/desktop.css
  code/matt_r/html/blog_lab/static/css/styles.css
  code/matt_r/html/blog_lab/static/img/em2_sedan.jpg
  code/matt_r/html/blog_lab/templates/blogmain.html
Labels: In Review

#228 Amber flask burrito
  code/amber/HTML_and_CSS/Flask/burrito.py
  code/amber/HTML_and_CSS/Flask/static/css/styles.css
  code/amber/HTML_and_CSS/Flask/static/img/artburrito.jpeg
  code/amber/HTML_and_CSS/Flask/static/img/babyburr.jpeg
  code/amber/HTML_and_CSS/Flask/static/img/brushburr.jpeg
  code/amber/HTML_and_CSS/Flask/static/img/creep.jpeg
  code/amber/HTML_and_CSS/Flask/static/img/headburr.jpeg
  code/amber/HTML_and_CSS/Flask/static/img/maburr.jpeg
  code/amber/HTML_and_CSS/Flask/static/img/yaburr.jpeg
  code/amber/HTML_and_CSS/Flask/templates/index.html
Labels: In Review

#219 ben_b-flask-lab04_burrito-WIP
  code/ben_b/Flask/lab04_burrito/burritos.jpg
  code/ben_b/Flask/lab04_burrito/index.html
  code/ben_b/Flask/lab04_burrito/mexican_food.jpg
  code/ben_b/Flask/lab04_burrito/styles.css
Labels: In Review

#208 company lab WIP
  code/ignacio/HTML_AND_CSS/company lab/images/bunny.jpeg
  code/ignacio/HTML_AND_CSS/company lab/images/chicken.jpeg
  code/ignacio/HTML_AND_CSS/company lab/images/chjansu.jpeg
  code/ignacio/HTML_AND_CSS/company lab/images/clothedsnake.jpeg
  code/ignacio/HTML_AND_CSS/company lab/images/coldweather.jpeg
  code/ignacio/HTML_AND_CSS/company lab/images/cosplay.jpeg
  code/ignacio/HTML_AND_CSS/company lab/images/giraffe.jpeg
  code/ignacio/HTML_AND_CSS/company lab/images/tophat.jpeg
  code/ignacio/HTML_AND_CSS/company lab/images/voodoohat.jpeg
  code/ignacio/HTML_AND_CSS/company lab/images/yeehaw.jpeg
  code/ignacio/HTML_AND_CSS/company lab/index.html
  code/ignacio/HTML_AND_CSS/company lab/static/desktopstyles.css
  code/ignacio/HTML_AND_CSS/company lab/static/mobilestyles.css
Labels: In Review

#202 ben_b-html_and_css-lab02_company-WIP
  code/ben_b/html_and_css/lab02_company/Wiki.jpg
  code/ben_b/html_and_css/lab02_company/desktopStyles.css
  code/ben_b/html_and_css/lab02_company/index.html
  code/ben_b/html_and_css/lab02_company/styles.css
Labels: In Review

#216 ignacio-r bloglab WIP
  code/ignacio/Flask/home.py
  code/ignacio/Flask/static/css/desktopstyles.css
  code/ignacio/Flask/static/css/styles.css
  code/ignacio/Flask/static/images/about page.jpeg
  code/ignacio/Flask/static/images/betterbg.webp
  code/ignacio/Flask/static/images/desktoplogo.jpeg
  code/ignacio/Flask/static/images/spider_man.0.jpg
  code/ignacio/Flask/templates/about.html
  code/ignacio/Flask/templates/index.html
Labels: In Review

#232 ben_b-html_and_css-lab05_portfolio-WIP
  code/ben_b/html_and_css/lab05_portfolio/backrooms.jpg
  code/ben_b/html_and_css/lab05_portfolio/desktopStyles.css
  code/ben_b/html_and_css/lab05_portfolio/index.html
  code/ben_b/html_and_css/lab05_portfolio/styles.css
Labels: Bonus Lab, WIP

#234 ignacio-r portforlio lab/WIP
  code/ignacio/HTML_AND_CSS/Personal Portfolio/index.html
  code/ignacio/HTML_AND_CSS/Personal Portfolio/static/css/mstyles.css
  code/ignacio/HTML_AND_CSS/Personal Portfolio/static/images/pokemon battle template.html
  code/ignacio/HTML_AND_CSS/Personal Portfolio/static/images/port inspirration.png
Labels: Bonus Lab, WIP

#235 mike_j-flask-html-css-lab5_personal_portfolio
  code/mike_j/flask_html_css/lab5_personal_portfolio/images/beer.jpg
  code/mike_j/flask_html_css/lab5_personal_portfolio/images/headshot.jpg
  code/mike_j/flask_html_css/lab5_personal_portfolio/images/kop.jpg
  code/mike_j/flask_html_css/lab5_personal_portfolio/images/pdx_skyline.jpg
  code/mike_j/flask_html_css/lab5_personal_portfolio/index.html
  code/mike_j/flask_html_css/lab5_personal_portfolio/styles.css
Labels: Bonus Lab, WIP

#239 Matt r html portfolio
  code/matt_r/html/Portfolio/profile.py
  code/matt_r/html/Portfolio/static/css/desktop.css
  code/matt_r/html/Portfolio/static/css/styles.css
  code/matt_r/html/Portfolio/static/img/M.PNG
  code/matt_r/html/Portfolio/static/img/self.jpg
  code/matt_r/html/Portfolio/templates/index.html
Labels: Bonus Lab, WIP

#240 mike_j-django-quickstart
  code/mike_j/django/django_quickstart/Pipfile
  code/mike_j/django/django_quickstart/myproject/manage.py
  code/mike_j/django/django_quickstart/myproject/myapp/__init__.py
  code/mike_j/django/django_quickstart/myproject/myapp/admin.py
  code/mike_j/django/django_quickstart/myproject/myapp/apps.py
  code/mike_j/django/django_quickstart/myproject/myapp/migrations/0001_initial.py
  code/mike_j/django/django_quickstart/myproject/myapp/migrations/0002_mymodel_timestamp.py
  code/mike_j/django/django_quickstart/myproject/myapp/migrations/__init__.py
  code/mike_j/django/django_quickstart/myproject/myapp/models.py
  code/mike_j/django/django_quickstart/myproject/myapp/templates/myapp/mytemplate.html
  code/mike_j/django/django_quickstart/myproject/myapp/tests.py
  code/mike_j/django/django_quickstart/myproject/myapp/urls.py
  code/mike_j/django/django_quickstart/myproject/myapp/views.py
  code/mike_j/django/django_quickstart/myproject/myproject/__init__.py
  code/mike_j/django/django_quickstart/myproject/myproject/asgi.py
  code/mike_j/django/django_quickstart/myproject/myproject/settings.py
  code/mike_j/django/django_quickstart/myproject/myproject/urls.py
  code/mike_j/django/django_quickstart/myproject/myproject/wsgi.py
Labels: Bonus Lab

#241 Amber django quickstart
  code/amber/django/django-quickstart/myproject/manage.py
  code/amber/django/django-quickstart/myproject/myapp/__init__.py
  code/amber/django/django-quickstart/myproject/myapp/admin.py
  code/amber/django/django-quickstart/myproject/myapp/apps.py
  code/amber/django/django-quickstart/myproject/myapp/migrations/0001_initial.py
  code/amber/django/django-quickstart/myproject/myapp/migrations/__init__.py
  code/amber/django/django-quickstart/myproject/myapp/models.py
  code/amber/django/django-quickstart/myproject/myapp/templates/myapp/mytemplate.html
  code/amber/django/django-quickstart/myproject/myapp/tests.py
  code/amber/django/django-quickstart/myproject/myapp/urls.py
  code/amber/django/django-quickstart/myproject/myapp/views.py
  code/amber/django/django-quickstart/myproject/myproject/__init__.py
  code/amber/django/django-quickstart/myproject/myproject/asgi.py
  code/amber/django/django-quickstart/myproject/myproject/settings.py
  code/amber/django/django-quickstart/myproject/myproject/urls.py
  code/amber/django/django-quickstart/myproject/myproject/wsgi.py
Labels: Bonus Lab

#242 lab for quickstart, no env, I built this yesterday
  code/Justin/Django/myproject/manage.py
  code/Justin/Django/myproject/myapp/__init__.py
  code/Justin/Django/myproject/myapp/admin.py
  code/Justin/Django/myproject/myapp/apps.py
  code/Justin/Django/myproject/myapp/migrations/0001_initial.py
  code/Justin/Django/myproject/myapp/migrations/0002_alter_mymodel_created.py
  code/Justin/Django/myproject/myapp/migrations/__init__.py
  code/Justin/Django/myproject/myapp/models.py
  code/Justin/Django/myproject/myapp/templates/myapp/home.html
  code/Justin/Django/myproject/myapp/tests.py
  code/Justin/Django/myproject/myapp/urls.py
  code/Justin/Django/myproject/myapp/views.py
  code/Justin/Django/myproject/myproject/__init__.py
  code/Justin/Django/myproject/myproject/asgi.py
  code/Justin/Django/myproject/myproject/settings.py
  code/Justin/Django/myproject/myproject/urls.py
  code/Justin/Django/myproject/myproject/wsgi.py
Labels: Bonus Lab

#245 ignacio-r django quickstart lab
  code/ignacio/django/django-quickstart/Pipfile
  code/ignacio/django/django-quickstart/Pipfile.lock
  code/ignacio/django/django-quickstart/myproject/manage.py
  code/ignacio/django/django-quickstart/myproject/myapp/__init__.py
  code/ignacio/django/django-quickstart/myproject/myapp/admin.py
  code/ignacio/django/django-quickstart/myproject/myapp/apps.py
  code/ignacio/django/django-quickstart/myproject/myapp/migrations/0001_initial.py
  code/ignacio/django/django-quickstart/myproject/myapp/migrations/__init__.py
  code/ignacio/django/django-quickstart/myproject/myapp/models.py
  code/ignacio/django/django-quickstart/myproject/myapp/templates/myapp/mytemplate.html
  code/ignacio/django/django-quickstart/myproject/myapp/tests.py
  code/ignacio/django/django-quickstart/myproject/myapp/urls.py
  code/ignacio/django/django-quickstart/myproject/myapp/views.py
  code/ignacio/django/django-quickstart/myproject/myproject/__init__.py
  code/ignacio/django/django-quickstart/myproject/myproject/asgi.py
  code/ignacio/django/django-quickstart/myproject/myproject/settings.py
  code/ignacio/django/django-quickstart/myproject/myproject/urls.py
  code/ignacio/django/django-quickstart/myproject/myproject/wsgi.py
Labels: Bonus Lab

#246 Nick Django Quickstart
  code/nick/django/django_quickstart/Pipfile
  code/nick/django/django_quickstart/myproject/manage.py
  code/nick/django/django_quickstart/myproject/myapp/__init__.py
  code/nick/django/django_quickstart/myproject/myapp/admin.py
  code/nick/django/django_quickstart/myproject/myapp/apps.py
  code/nick/django/django_quickstart/myproject/myapp/migrations/0001_initial.py
  code/nick/django/django_quickstart/myproject/myapp/migrations/0002_alter_mymodel_content.py
  code/nick/django/django_quickstart/myproject/myapp/migrations/__init__.py
  code/nick/django/django_quickstart/myproject/myapp/models.py
  code/nick/django/django_quickstart/myproject/myapp/templates/myapp/mytemplate.html
  code/nick/django/django_quickstart/myproject/myapp/tests.py
  code/nick/django/django_quickstart/myproject/myapp/urls.py
  code/nick/django/django_quickstart/myproject/myapp/views.py
  code/nick/django/django_quickstart/myproject/myproject/__init__.py
  code/nick/django/django_quickstart/myproject/myproject/asgi.py
  code/nick/django/django_quickstart/myproject/myproject/settings.py
  code/nick/django/django_quickstart/myproject/myproject/urls.py
  code/nick/django/django_quickstart/myproject/myproject/wsgi.py
Labels: Bonus Lab
